/**
 * @license
 * Copyright 2025 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with a copy of the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { projectRoot } from '#common/utils.js';
import { BuildablePackage } from '#common/types.js';

/**
 * Generates a date-based version string with an incremental patch.
 * Format: YYYYMMDD.hour.patch
 * The patch number is incremented based on the last version stored in the
 * sa360 version file, resetting when the hour changes.
 *
 * @param projectRoot The root directory of the project.
 * @returns The new version string.
 */
export async function getNextVersion(
  packageDir: BuildablePackage,
): Promise<string> {
  const now = new Date();
  const startOfDay = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()),
  );
  const elapsedMilliseconds = now.getTime() - startOfDay.getTime();
  const hours = Math.floor(elapsedMilliseconds / (1000 * 60 * 60));

  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, '0');
  const day = String(now.getUTCDate()).padStart(2, '0');

  const dateAndHourPart = `${year}${month}${day}.${hours}`;

  let patch = 0;
  try {
    const versionFilePath = path.resolve(
      projectRoot,
      packageDir,
      'src',
      'version.ts',
    );
    const content = await fs.readFile(versionFilePath, 'utf-8');
    const match = content.match(
      /global\.CURRENT_SHEET_VERSION = '(\d{8}\.\d+).(\d+)'/,
    );
    console.trace({ match });
    if (match) {
      const lastDateAndHourPart = match[1];
      const lastVersionPatch = Number(match[2]);

      if (dateAndHourPart === lastDateAndHourPart) {
        patch = lastVersionPatch + 1;
      }
    }
  } catch (_) {
    // File doesn't exist or couldn't be read, start patch at 0.
  }

  return `${dateAndHourPart}.${patch}`;
}

/**
 * Writes the version file to the specified product directory.
 *
 * @param packageDir The product to write the version file for (e.g., 'dv360').
 * @param version The version string to write.
 * @param projectRoot The root directory of the project.
 */
export async function writeVersionFile(
  packageDir: BuildablePackage,
  version: string,
  projectRoot: string,
) {
  const content = `/**
 * @license
 * Copyright 2025 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with a copy of the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT. This file is automatically generated by common/generate-version.ts
global.CURRENT_SHEET_VERSION = '${version}';
`;
  const versionFilePath = path.resolve(
    projectRoot,
    packageDir,
    'src',
    'version.ts',
  );
  await fs.writeFile(versionFilePath, content, 'utf-8');
}
