#!/usr/bin/env node
/**
 * @license
 * Copyright 2024 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { writeFile } from 'fs/promises';
import { resolve } from 'path';

/**
 * Generates a date-based version string.
 * Format: YYYYMMDD.secondsSinceUTCMidnight
 */
function getVersion() {
  const now = new Date();
  const startOfDay = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()),
  );
  const secondsSinceMidnight = Math.floor(
    (now.getTime() - startOfDay.getTime()) / 1000,
  );

  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, '0');
  const day = String(now.getUTCDate()).padStart(2, '0');

  return `${year}${month}${day}.${secondsSinceMidnight}`;
}

async function main() {
  const version = getVersion();
  const content = `/**
 * @license
 * Copyright 2024 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT. This file is automatically generated by scripts/generate-version.mjs
export const CURRENT_SHEET_VERSION = '${version}';
`;

  const products = ['dv360', 'sa360'];
  for (const product of products) {
    const versionFilePath = resolve(
      process.cwd(),
      product,
      'src',
      'version.ts',
    );
    await writeFile(versionFilePath, content, 'utf-8');
    console.log(`Wrote version ${version} to ${product}/src/version.ts`);
  }
}

main();
