// Sheet Names
REPORTS_CONFIG_SHEET_NAME = 'Reports Config';
USE_CASES_CONFIG_SHEET_NAME = 'Use Cases Config';
// Use Cases Sheet Names
GHOST_PLACEMENTS_SHEET_NAME = 'Ghost Placements';
DEFAULT_ADS_RATE_SHEET_NAME = 'Default Ads Rate';
// REPORTS_CONFIG_SHEET_NAME Column indexes
REPORTS_CONFIG_ROW_START = 2;
REPORTS_CONFIG_COL_START = 1;
REPORTS_CONFIG_USE_CASE_COLUMN = 1;
REPORTS_CONFIG_PROFILE_ID_COLUMN = 2;
REPORTS_CONFIG_ACCOUNT_ID_COLUMN = 3;
REPORTS_CONFIG_REPORT_ID_COLUMN = 4;
REPORTS_CONFIG_REPORT_DATE_RANGE = 5;
REPORTS_CONFIG_FILTERS_COLUMN = 6; 
REPORTS_CONFIG_THRESHOLD_COLUMN = 7; 
REPORTS_CONFIG_EXTRA_PARAMS_COLUMN = 8; 
REPORTS_CONFIG_EMAILS_COLUMN = 9;
REPORTS_CONFIG_EMAIL_MESSAGE_COLUMN = 10;
REPORTS_CONFIG_ENABLED_COLUMN = 11;
REPORTS_CONFIG_EXECUTION_STATUS_COLUMN = 12;
REPORTS_CONFIG_LAST_EXECUTION_COLUMN = 13;
// REPORT_DATA_SHEET_NAME Columns indexes
REPORT_DATA_ADVERTISER_COLUMN = 3;
// USE_CASES_CONFIG_SHEET_NAME Columns indexes
USE_CASES_CONFIG_ROW_START = 2;
USE_CASES_CONFIG_COL_START = 1;
USE_CASES_CONFIG_NAME_COLUMN = 0;
USE_CASES_CONFIG_THRESHOLD_COLUMN = 3;
// Other Configs
RED_RGB_COLOR = '#ea4335';
BLUE_RGB_COLOR = '#4285f4';
// Use Cases Keys
GHOST_PLACEMENTS_KEY = 'GHOST_PLACEMENTS';
DEFAULT_ADS_RATE_KEY = 'DEFAULT_ADS_RATE';
FLOODLIGHT_TRENDS_KEY = 'FLOODLIGHT_TRENDS';
OUT_OF_FLIGHT_PLACEMENTS_KEY = 'OUT_OF_FLIGHT_PLACEMENTS';
TRACKING_ADS_KEY = 'TRACKING_ADS';

// General Use Case Alerts
WEEK_LABEL_HEADER = 'Week Label'
FLAG_COLUMN_HEADER = 'Flag';
BROKEN_RULES_COLUMN_HEADER = 'Rules';

// Ghost Placements Alerts
GP_DATE_COLUMN = 1;
GP_ADVERTISER_NAME_COLUMN = 3;
GP_CAMPAIGN_NAME_COLUMN = 5;
GP_PLACEMENT_ID_COLUMN = 7;
GP_PLACEMENT_NAME_COLUMN = 8;
GP_TOTAL_CONVERSIONS_COLUMN = 11;

// Default Ads Rate Alerts
DA_DATE_COLUMN = 1;
DA_PLACEMENT_ID_COLUMN = 7;
DA_PLACEMENT_NAME_COLUMN = 8;
DA_AD_TYPE_COLUMN = 11;
DA_IMPRESSIONS_COLUMN = 12;
DA_DEFAULT_AD_TYPE = 'Default';

// Floodlight Trends
FT_WEEK_COLUMN = 2;
FT_FLOODLIGHT_CONFIG_COLUMN = 3;
FT_ACTIVITY_ID_COLUMN = 4;
FT_ACTIVITY_NAME_COLUMN = 5;
FT_FLOODLIGHT_IMPRESSIONS_COLUMN = 6;

// Out of Flight Placements
OFP_DATE_COLUMN = 1;
OFP_PLACEMENT_ID_COLUMN = 7;
OFP_PLACEMENT_END_DATE_COLUMN = 10;
OFP_IMPRESSIONS_COLUMN = 11;

// Tracking Ads
TA_DATE_COLUMN = 1;
TA_PLACEMENT_ID_COLUMN = 7;
TA_PLACEMENT_NAME_COLUMN = 8;
TA_IMPRESSIONS_COLUMN = 9;
TA_CLICKS_COLUMN = 10;