// Sheet Names
let REPORTS_CONFIG_SHEET_NAME = 'Reports Config';
let USE_CASES_CONFIG_SHEET_NAME = 'Use Cases Config';
// Use Cases Sheet Names
let GHOST_PLACEMENTS_SHEET_NAME = 'Ghost Placements';
let DEFAULT_ADS_RATE_SHEET_NAME = 'Default Ads Rate';
// REPORTS_CONFIG_SHEET_NAME Column indexes
let REPORTS_CONFIG_ROW_START = 2;
let REPORTS_CONFIG_COL_START = 1;
let REPORTS_CONFIG_USE_CASE_COLUMN = 1;
let REPORTS_CONFIG_PROFILE_ID_COLUMN = 2;
let REPORTS_CONFIG_ACCOUNT_ID_COLUMN = 3;
let REPORTS_CONFIG_REPORT_ID_COLUMN = 4;
let REPORTS_CONFIG_REPORT_DATE_RANGE = 5;
let REPORTS_CONFIG_FILTERS_COLUMN = 6;
let REPORTS_CONFIG_THRESHOLD_COLUMN = 7;
let REPORTS_CONFIG_EXTRA_PARAMS_COLUMN = 8;
let REPORTS_CONFIG_EMAILS_COLUMN = 9;
let REPORTS_CONFIG_EMAIL_MESSAGE_COLUMN = 10;
let REPORTS_CONFIG_ENABLED_COLUMN = 11;
let REPORTS_CONFIG_EXECUTION_STATUS_COLUMN = 12;
let REPORTS_CONFIG_LAST_EXECUTION_COLUMN = 13;
// REPORT_DATA_SHEET_NAME Columns indexes
let REPORT_DATA_ADVERTISER_COLUMN = 3;
// USE_CASES_CONFIG_SHEET_NAME Columns indexes
let USE_CASES_CONFIG_ROW_START = 2;
let USE_CASES_CONFIG_COL_START = 1;
let USE_CASES_CONFIG_NAME_COLUMN = 0;
let USE_CASES_CONFIG_THRESHOLD_COLUMN = 3;
// Other Configs
let RED_RGB_COLOR = '#ea4335';
let BLUE_RGB_COLOR = '#4285f4';
// Use Cases Keys
let GHOST_PLACEMENTS_KEY = 'GHOST_PLACEMENTS';
let DEFAULT_ADS_RATE_KEY = 'DEFAULT_ADS_RATE';
let FLOODLIGHT_TRENDS_KEY = 'FLOODLIGHT_TRENDS';
let OUT_OF_FLIGHT_PLACEMENTS_KEY = 'OUT_OF_FLIGHT_PLACEMENTS';
let TRACKING_ADS_KEY = 'TRACKING_ADS';
let DEFAULT_LANDING_PAGE_KEY = 'DEFAULT_LANDING_PAGE';

// General Use Case Alerts
let WEEK_LABEL_HEADER = 'Week Label';
let FLAG_COLUMN_HEADER = 'Flag';
let BROKEN_RULES_COLUMN_HEADER = 'Rules';

// Ghost Placements Alerts
let GP_DATE_COLUMN = 1;
let GP_ADVERTISER_NAME_COLUMN = 3;
let GP_CAMPAIGN_NAME_COLUMN = 5;
let GP_PLACEMENT_ID_COLUMN = 7;
let GP_PLACEMENT_NAME_COLUMN = 8;
let GP_TOTAL_CONVERSIONS_COLUMN = 11;

// Default Ads Rate Alerts
let DA_DATE_COLUMN = 1;
let DA_PLACEMENT_ID_COLUMN = 7;
let DA_PLACEMENT_NAME_COLUMN = 8;
let DA_AD_TYPE_COLUMN = 11;
let DA_IMPRESSIONS_COLUMN = 12;
let DA_DEFAULT_AD_TYPE = 'Default';

// Floodlight Trends
let FT_WEEK_COLUMN = 2;
let FT_FLOODLIGHT_CONFIG_COLUMN = 3;
let FT_ACTIVITY_ID_COLUMN = 4;
let FT_ACTIVITY_NAME_COLUMN = 5;
let FT_FLOODLIGHT_IMPRESSIONS_COLUMN = 6;

// Out of Flight Placements
let OFP_DATE_COLUMN = 1;
let OFP_PLACEMENT_ID_COLUMN = 7;
let OFP_PLACEMENT_END_DATE_COLUMN = 10;
let OFP_IMPRESSIONS_COLUMN = 11;

// Tracking Ads
let TA_DATE_COLUMN = 1;
let TA_PLACEMENT_ID_COLUMN = 7;
let TA_PLACEMENT_NAME_COLUMN = 8;
let TA_IMPRESSIONS_COLUMN = 9;
let TA_CLICKS_COLUMN = 10;

// Default Landing Page
let DLP_DATE_COLUMN = 1;
let DLP_LANDING_PAGE_COLUMN = 8;
