/**
 * @license
 * Copyright 2024 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ParamDefinition, SettingMapInterface } from 'common/types';

/**
 * Provides a useful data structure to get campaign ID settings.
 *
 * Defaults to the row with campaignId: 'default' if no campaign ID override is
 * set.
 */
export class SettingMap<P extends { [Property in keyof P]: P[keyof P] }>
  implements SettingMapInterface<P>
{
  private readonly map: Map<string, P>;
  private readonly keys: Array<keyof P>;

  constructor(values: Array<[string, P]>) {
    this.map = new Map(values);
    if (values.length > 0 && values[0] && values[0][1]) {
      this.keys = Object.keys(values[0][1]) as Array<keyof P>;
    } else {
      this.keys = [];
    }
  }

  toJSON() {
    return Object.fromEntries(this.map);
  }

  get(id: string): P {
    const obj = this.map.get(id);
    if (obj) {
      return obj;
    }
    const newObj = Object.fromEntries(this.keys.map((k) => [k, ''])) as P;
    this.map.set(id, newObj);
    return newObj;
  }

  getOrDefault(id: string): P {
    const defaultValue =
      this.map.get('default') || ({} as Record<keyof P, string>);
    const campaignValue = this.map.get(id) || ({} as Record<keyof P, string>);
    return this.keys.reduce(
      (prev, key) => {
        prev[key] =
          (!(key in campaignValue) || !campaignValue[key]
            ? defaultValue[key]
            : campaignValue[key]) ?? '';
        return prev;
      },

      {} as Record<keyof P, string>,
    ) as P;
  }

  entries(): ReadonlyArray<[string, string[]]> {
    const arr: Array<[string, string[]]> = [];
    for (const [id, row] of this.map.entries()) {
      arr.push([id, Object.values(row)]);
    }
    return arr;
  }

  set(id: string, setting: P) {
    this.map.set(id, setting);
  }
}

/**
 * Converts a settings 2-d array to an internal data structure.
 *
 * The 2-d array has headers as parameters and rows as campaign IDs.
 *
 * Example in CSV form:
 *
 *    campaignID, campaignName, My Param 1, My Param 2
 *    default,,hello,world
 *    1, acme campaign, foo, bar
 *
 * Note  two columns in the front which include the campaign ID and campaign
 * name.
 *
 * There's also allowance for a single "default" column without a campaign name.
 *
 * @param rawSettings A 2-d array (usually auto-generated by this app)
 * @param mapper Maps internal params to the user-facing definition
 *     e.g. {param1: {title: 'My Param 1'}}
 */
export function transformToParamValues<
  MapType extends Record<keyof MapType, ParamDefinition>,
>(rawSettings: ReadonlyArray<string[]>, mapper: MapType) {
  if (rawSettings.length < 2) {
    throw new Error(
      'Expected a grid with row and column headers of at least size 2',
    );
  }
  const headers = rawSettings[0];
  const body = rawSettings.slice(1);

  function forEachRow(
    row: readonly string[],
  ): [string, { [Property in keyof MapType]: string }] {
    return [
      row[0],
      Object.fromEntries(
        Object.entries<ParamDefinition>(mapper).map(([param, { label }]) => {
          const i = headers.indexOf(label);
          return [param, row[i]];
        }),
      ) as { [Property in keyof MapType]: string },
    ];
  }
  const mapped = body.map(forEachRow);
  const postMap = new SettingMap(mapped);
  return postMap;
}

export function makeCampaignIndexedSettings(
  headers: string[],
  currentSettings: string[][],
): Record<string, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};
  for (let i = 0; i < currentSettings.length; i++) {
    const campaignId = currentSettings[i][0];
    for (let c = 1; c < currentSettings[i].length; c++) {
      (result[campaignId] = result[campaignId] ?? {})[headers[c - 1]] =
        currentSettings[i][c];
    }
  }
  return result;
}
